### ISSUE TITLE
Operation check: is it still working?

### ISSUE THREAD

**Issue by andygodber** [szech/mmm-uk-pollen-forecast#5]
Couldnt get any content - note the point about MetOffice changes, but want to check if anyone else is still working?

**Comment by r4zi3lrrr** [comment]
Doesn't work me either - no content.

Damn shame as there doesn't seem to be anymore pollen modules for the UK (that I could find).

**Comment by r4zi3lrrr** [comment]
I did try to run the npm install -g command as per read.me and got this:

admin@rpi-mirror:~/MagicMirror/modules/mmm-uk-pollen-forecast $ npm install -g
npm error code EACCES
npm error syscall symlink
npm error path ../../../home/admin/MagicMirror/modules/mmm-uk-pollen-forecast
npm error dest /usr/lib/node_modules/mmm-uk-pollen-forecast
npm error errno -13
npm error Error: EACCES: permission denied, symlink '../../../home/admin/MagicMirror/modules/mmm-uk-pollen-forecast' -> '/usr/lib/node_modules/mmm-uk-pollen-forecast'
npm error     at async symlink (node:internal/fs/promises:1002:10)
npm error     at async /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:715:7
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'symlink',
npm error   path: '../../../home/admin/MagicMirror/modules/mmm-uk-pollen-forecast',
npm error   dest: '/usr/lib/node_modules/mmm-uk-pollen-forecast'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.
npm error A complete log of this run can be found in: /home/admin/.npm/_logs/2024-07-05T11_00_36_669Z-debug-0.log

**Comment by r4zi3lrrr** [comment]
Tried with sudo

admin@rpi-mirror:~/MagicMirror/modules/mmm-uk-pollen-forecast $ sudo npm install -g

added 1 package in 5s

Still not working - doesn't load any content.

**Comment by szech** [comment]
Sorry guys, just noticed its not working. I will investigate :)

**Comment by szech** [comment]
should be fixed in latest version [1.0.3](https://github.com/szech/mmm-uk-pollen-forecast/releases/tag/1.0.3).
will close this issue if no one finds any problems.
